steamcl-install: Add support for verbose flag, replace --restrict with --flags
With this commit, we now pass flags with --flags, for example:

    steamcl-install --flags restricted,verbose

And the behavior is as following:
- without --flags, then steamcl-install doesn't care about flag files:
  no addition, no deletion.
- with --flags, then steamcl-install installs the flag files that are
  passed, and removes the flag files that were not passed.

This option impacts flag files in ESPDIR/efi/steamos, and if the option
--install-extra-removable was specified, it also impacts flag files in
ESPDIR/efi/boot.

The flags currently supported are:
- 'restricted': which installs a file steamcl-restricted
- 'verbose'   : which installs a file steamcl-verbose

Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>

diff --git a/util/steamcl-install.in b/util/steamcl-install.in
--- a/util/steamcl-install.in
+++ b/util/steamcl-install.in
@@ -53,9 +53,12 @@ manifest_version=;
 checksum=;
 installpath=EFI/$distrib;
 
+flags=; # comma separated list of flags
 force_extra_removable=0;
 force_removable_efiboot=0;
-restrict=0
+
+restricted=0;
+verbose=0;
 
 warn () { echo "$@" >&2; }
 
@@ -310,7 +313,6 @@ update_esp ()
     local esp=$1; shift;
     local bin=$1; shift;
     local ver=$1; shift;
-    local flagsdir=/"$dst";
     local bootdir=/efi/"$dst";
     local bootnum=;
     local entry=;
@@ -341,21 +343,45 @@ update_esp ()
     if [ $force_extra_removable = 1 ];
     then
         bootdir=/efi/boot/;
+
         echo "Installing bootloader to the removable media path @ $bootdir/bootx64.efi";
         mkdir -p $esp$bootdir;
         cp -av $bin $esp$bootdir/bootx64.efi;
         # not installing the .version file
     fi
 
-    if [ $restrict = 1 ];
+    return 0;
+}
+
+update_flags ()
+{
+    local dst=$1; shift;
+    local esp=$1; shift;
+    declare -a bootdirs;
+
+    bootdirs+=(/efi/"$dst");
+    if [ $force_extra_removable = 1 ];
     then
-        echo "Enabling restricted flag @ $flagsdir/restricted";
-        mkdir -p $esp$flagsdir;
-        touch $esp$flagsdir/restricted;
-        echo "-> '$esp$flagsdir/restricted'";
+        bootdirs+=(/efi/boot/);
     fi;
 
-    return 0;
+    for bootdir in "${bootdirs[@]}";
+    do
+        for flag in restricted verbose;
+        do
+            local flagfile="steamcl-$flag";
+            if [ ${!flag} = 1 ] && [ ! -e ${bootdir}/${flagfile} ];
+            then
+                echo "Enabling flag @ ${bootdir}/${flagfile}";
+                touch ${esp}${bootdir}/${flagfile};
+                echo "-> '${esp}${bootdir}/${flagfile}'";
+            elif [ ${!flag} = 0 ] && [ -e ${bootdir}/${flagfile} ];
+            then
+                echo "Removing flag @ ${bootdir}/${flagfile}";
+                rm -fv ${esp}${bootdir}/${flagfile};
+            fi;
+        done;
+    done;
 }
 
 add_boot_entry ()
@@ -466,6 +492,12 @@ need_new_efi_boot_entry ()
 while [ "$#" -gt 0 ];
 do
     case "$1" in
+        (--flags)
+            shift;
+            flags=$1;
+            shift;
+            ;;
+
         (--force-extra-removable)
             force_extra_removable=1;
             shift;
@@ -476,13 +508,26 @@ do
             shift;
             ;;
 
-        (--restrict)
-            restrict=1;
-            shift;
+        (*)
+            warn "Unexpected argument '$1'";
+            exit 1;
+            ;;
+    esac
+done
+
+for f in ${flags//,/ };
+do
+    case $f in
+        (restricted)
+            restricted=1;
+            ;;
+
+        (verbose)
+            verbose=1;
             ;;
 
         (*)
-            warn "Unexpected argument '$1'";
+            warn "Invalid flag $f";
             exit 1;
             ;;
     esac
@@ -560,6 +605,11 @@ then
         echo " " checksum: $checksum;
         echo " " expected: $pkg_checksum;
     fi;
+fi;
+
+if [ -n "$flags" ];
+then
+    update_flags $distrib $esp_mount;
 fi;
 
 if [ $esp_boot_ok = 0 ];
